#!/bin/sh
### BEGIN INIT INFO
# Provides: Block exporter
# Required-Start: $local_fs $network $named $time $syslog
# Required-Stop: $local_fs $network $named $time $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Block exporter for prometheus written in Python
### END INIT INFO

NAME=block_exporter
USER=ubuntu
CMD="/usr/bin/python /home/$USER/block-exporter/block-exporter.py"
PIDFILE=/var/run/prometheus/$NAME.pid
LOGFILE=/var/log/prometheus/$NAME.log

ARGS=""
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

do_start_prepare()
{
  mkdir -p `dirname $PIDFILE` || true
  mkdir -p `dirname $LOGFILE` || true
  chown -R $USER: `dirname $LOGFILE`
  chown -R $USER: `dirname $PIDFILE`
}

do_start_cmd()
{
  do_start_prepare
  echo -n "Starting daemon: "$NAME
  start-stop-daemon --chuid $USER -C --background --start --quiet --pidfile $PIDFILE --make-pidfile --exec $CMD -- $ARGS >> $LOGFILE 2>&1
  echo "."
}

do_stop_cmd()
{
  echo -n "Stopping daemon: "$NAME
  start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
  rm $PIDFILE
  echo "."
}

status() {
  printf "%-50s" "Checking $NAME..."
  if [ -f $PIDFILE ]; then
    PID=$(cat $PIDFILE)
    if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
      printf "%s\n" "The process appears to be dead but pidfile still exists"
    else
      echo "Running, the PID is $PID"
    fi
  else
    printf "%s\n" "Service not running"
  fi
}

case "$1" in
  start)
    do_start_cmd
    ;;
  stop)
    do_stop_cmd
    ;;
  status)
    status
    ;;
  restart)
    do_stop_cmd
    do_start_cmd
    ;;
  *)
    echo "Usage: $1 {start|stop|status|restart}"
    exit 1
esac

exit 0
